export interface Product {
  id: number
  name: string
  category: string
  price: string
  image: string
  description: string
  available: boolean
  rating: number
}

export const categories = [
  "Semua",
  "Barang 1",
  "Barang 2",
  "Barang 3",
  "Barang 4",
  "Barang 5",
]

export const products: Product[] = [
  {
    id: 1,
        name: "meja prasmanan",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Meja panjang yang kokoh dan elegan, ideal untuk menyajikan hidangan prasmanan di berbagai acara.",
    available: true,
    rating: 5.0,
  },
  {
    id: 2,
    name: "meja sidang uk.60x220",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Meja sidang berukuran 60x220 cm, cocok untuk rapat formal, konferensi, atau sebagai meja display.",
    available: true,
    rating: 5.0,
  },
  {
    id: 3,
    name: "meja sidang kecil",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Meja sidang berukuran lebih ringkas, sempurna untuk diskusi kelompok kecil atau ruang terbatas.",
    available: true,
    rating: 5.0,
  },
  {
    id: 4,
    name: "meja bulat",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Meja bundar serbaguna yang mendorong interaksi, ideal untuk acara makan malam atau diskusi santai.",
    available: true,
    rating: 5.0,
  },
  {
    id: 5,
    name: "oscar",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Kursi Oscar yang mewah dan nyaman, memberikan sentuhan elegan untuk tamu VIP atau acara spesial.",
    available: true,
    rating: 5.0,
  },
  {
    id: 6,
    name: "saten",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sarung kursi berbahan saten mengkilap, menambah kesan mewah dan formal pada dekorasi acara Anda.",
    available: true,
    rating: 5.0,
  },
  {
    id: 7,
    name: "runner",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Runner meja dekoratif untuk mempercantik tampilan meja makan, tersedia dalam berbagai warna dan motif.",
    available: true,
    rating: 5.0,
  },
  {
    id: 8,
    name: "gombyok",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Hiasan rumbai (gombyok) untuk tenda atau panggung, memberikan sentuhan tradisional dan meriah.",
    available: true,
    rating: 5.0,
  },
  {
    id: 9,
    name: "taplak kain kaca",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Taplak meja transparan dari bahan kain kaca, melindungi meja sambil tetap menonjolkan keindahannya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 10,
    name: "renda sulur",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Renda dengan motif sulur yang cantik, cocok untuk menghias tepi taplak meja atau dekorasi lainnya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 11,
    name: "kain batik",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Kain batik dengan corak klasik dan modern, serbaguna untuk taplak meja, backdrop, atau hiasan.",
    available: true,
    rating: 5.0,
  },
  {
    id: 12,
    name: "rompi hitam",
    category: "Barang 1",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Rompi hitam formal untuk staf atau pramusaji, memberikan penampilan yang profesional dan seragam.",
    available: true,
    rating: 5.0,
  },
  {
    id: 13,
    name: "piring makan",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Piring makan keramik standar berdiameter ideal, cocok untuk menyajikan hidangan utama.",
    available: true,
    rating: 5.0,
  },
  {
    id: 14,
    name: "piring makan ceper",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Piring makan model ceper (datar), sempurna untuk penyajian hidangan modern dan artistik.",
    available: true,
    rating: 5.0,
  },
  {
    id: 15,
    name: "piring salad",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Piring berukuran sedang yang dirancang khusus untuk menyajikan aneka salad segar dan hidangan pembuka.",
    available: true,
    rating: 5.0,
  },
  {
    id: 16,
    name: "mangkuk puding",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk kecil yang elegan, ideal untuk menyajikan puding, es krim, atau hidangan penutup lainnya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 17,
    name: "mangkuk tahu campur",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk dengan ukuran pas untuk menyajikan hidangan khas seperti tahu campur atau lontong balap.",
    available: true,
    rating: 5.0,
  },
  {
    id: 18,
    name: "mangkuk bakso",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk bakso klasik yang tebal dan tahan panas, menjaga kehangatan kuah lebih lama.",
    available: true,
    rating: 5.0,
  },
  {
    id: 19,
    name: "mangkuk soto",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk soto berdesain khas, cocok untuk menyajikan soto, rawon, atau hidangan berkuah lainnya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 20,
    name: "mangkuk sup sango bulat",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk sup Sango berkualitas dengan desain bulat minimalis, menambah keanggunan meja makan.",
    available: true,
    rating: 5.0,
  },
  {
    id: 21,
    name: "mangkuk sup consome",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk sup consome dengan dua pegangan, memudahkan tamu menikmati sup panas dengan nyaman.",
    available: true,
    rating: 5.0,
  },
  {
    id: 22,
    name: "mangkuk sup melamin",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk sup dari bahan melamin yang ringan dan tidak mudah pecah, aman untuk berbagai acara.",
    available: true,
    rating: 5.0,
  },
  {
    id: 23,
    name: "lepek kue sango",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Lepek atau piring kecil Sango, cocok untuk alas cangkir atau menyajikan kue-kue kecil.",
    available: true,
    rating: 5.0,
  },
  {
    id: 24,
    name: "lepek kue melamin kotak",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Lepek kue melamin berbentuk kotak, memberikan sentuhan modern untuk penyajian snack atau kue.",
    available: true,
    rating: 5.0,
  },
  {
    id: 25,
    name: "lepek melamin bulat",
    category: "Barang 2",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Lepek melamin bulat klasik, serbaguna untuk alas cangkir, tatakan, atau piring kue.",
    available: true,
    rating: 5.0,
  },
  {
    id: 26,
    name: "sendok sup melamin",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok sup bebek dari bahan melamin, ringan dan ideal untuk hidangan sup Asia.",
    available: true,
    rating: 5.0,
  },
  {
    id: 27,
    name: "sendok sup sango",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok sup Sango dari stainless steel berkualitas, dengan desain elegan dan nyaman digenggam.",
    available: true,
    rating: 5.0,
  },
  {
    id: 28,
    name: "sendok bulat ",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok dengan kepala bulat (dessert spoon), cocok untuk hidangan penutup, sereal, atau sup.",
    available: true,
    rating: 5.0,
  },
  {
    id: 29,
    name: "sendok kecil ",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok teh kecil, ideal untuk mengaduk minuman panas atau sebagai sendok hidangan penutup.",
    available: true,
    rating: 5.0,
  },
  {
    id: 30,
    name: "garpu kecil",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Garpu kue atau garpu dessert, berukuran kecil untuk menikmati kue, buah, atau hidangan pembuka.",
    available: true,
    rating: 5.0,
  },
  {
    id: 31,
    name: "sendok makan",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok makan standar dari stainless steel, esensial untuk setiap acara makan.",
    available: true,
    rating: 5.0,
  },
  {
    id: 32,
    name: "garpu makan",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Garpu makan standar dari stainless steel, pasangan sempurna untuk sendok makan.",
    available: true,
    rating: 5.0,
  },
  {
    id: 33,
    name: "sendok makan contesa",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok makan model Contesa dengan ukiran elegan di gagang, menambah kemewahan.",
    available: true,
    rating: 5.0,
  },
  {
    id: 34,
    name: "garpu makan contesa",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Garpu makan model Contesa, serasi dengan sendok Contesa untuk set peralatan makan yang mewah.",
    available: true,
    rating: 5.0,
  },
  {
    id: 35,
    name: "sendok salad",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok besar khusus untuk mengambil dan menyajikan salad dari mangkuk saji.",
    available: true,
    rating: 5.0,
  },
  {
    id: 36,
    name: "garpu salad",
    category: "Barang 3",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Garpu besar dengan gigi lebar, dirancang untuk menyajikan dan mencampur salad.",
    available: true,
    rating: 5.0,
  },
  {
    id: 37,
    name: "roll top bulat besar",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas saji (chafing dish) model roll top bulat, menjaga makanan tetap hangat dengan elegan.",
    available: true,
    rating: 5.0,
  },
  {
    id: 38,
    name: "roll top kotak",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas saji (chafing dish) model roll top kotak, ideal untuk hidangan utama di meja buffet.",
    available: true,
    rating: 5.0,
  },
  {
    id: 39,
    name: "roll top kotak double inset",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas roll top kotak dengan dua wadah (inset), memungkinkan penyajian dua jenis lauk sekaligus.",
    available: true,
    rating: 5.0,
  },
  {
    id: 40,
    name: "pemanas besar sunex",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas makanan Sunex berukuran besar, handal untuk menjaga kehangatan hidangan dalam jumlah banyak.",
    available: true,
    rating: 5.0,
  },
  {
    id: 41,
    name: "pemanas besar sunex double inset",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas Sunex besar dengan dua wadah, efisien untuk menyajikan variasi menu di acara besar.",
    available: true,
    rating: 5.0,
  },
  {
    id: 42,
    name: "pemanas kuningan",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas makanan dengan aksen kuningan yang mewah, memberikan sentuhan klasik dan premium.",
    available: true,
    rating: 5.0,
  },
  {
    id: 43,
    name: "sup turin",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Wadah saji sup (soup tureen) yang elegan, lengkap dengan tutup dan sendok sayur.",
    available: true,
    rating: 5.0,
  },
  {
    id: 44,
    name: "pemanas kecil",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas makanan berukuran kecil, cocok untuk lauk pendamping, saus, atau acara dengan tamu terbatas.",
    available: true,
    rating: 5.0,
  },
  {
    id: 45,
    name: "pemanas bulat",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas saji berbentuk bulat, ideal untuk hidangan seperti sup, bubur, atau semur.",
    available: true,
    rating: 5.0,
  },
  {
    id: 46,
    name: "pemanas kaca",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pemanas makanan dengan tutup kaca transparan, memudahkan tamu melihat isi hidangan tanpa membukanya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 47,
    name: "inset pemanas besar",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Wadah (inset) stainless steel pengganti untuk pemanas makanan ukuran besar.",
    available: true,
    rating: 5.0,
  },
  {
    id: 48,
    name: "inset pemanas kecil",
    category: "Barang 4",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Wadah (inset) stainless steel pengganti untuk pemanas makanan ukuran kecil.",
    available: true,
    rating: 5.0,
  },
  {
    id: 49,
    name: "sendok ikan",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok khusus untuk menyajikan hidangan ikan, membantu mengambil daging ikan tanpa merusaknya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 50,
    name: "japit ikan/kue",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Penjepit serbaguna dari stainless steel, ideal untuk mengambil potongan kue, roti, atau lauk.",
    available: true,
    rating: 5.0,
  },
  {
    id: 51,
    name: "erus",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok sayur atau irus, alat esensial untuk mengambil hidangan berkuah dari panci atau pemanas.",
    available: true,
    rating: 5.0,
  },
  {
    id: 52,
    name: "entong nasi",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sendok nasi besar (entong) untuk mengambil dan menyajikan nasi dari rice cooker atau wadah saji.",
    available: true,
    rating: 5.0,
  },
  {
    id: 53,
    name: "garpu ikan",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Garpu khusus untuk hidangan ikan, dirancang untuk memisahkan duri dan daging dengan mudah.",
    available: true,
    rating: 5.0,
  },
  {
    id: 54,
    name: "skop puding",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Sekop kecil dengan ujung datar, sempurna untuk memotong dan menyajikan puding atau kue tart.",
    available: true,
    rating: 5.0,
  },
  {
    id: 55,
    name: "pisau steak",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Pisau steak dengan gerigi tajam, memastikan potongan daging yang rapi dan mudah.",
    available: true,
    rating: 5.0,
  },
  {
    id: 56,
    name: "skal bulat melamin",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Piring saji atau 'skal' bulat dari bahan melamin, ringan dan cocok untuk buah atau jajanan pasar.",
    available: true,
    rating: 5.0,
  },
  {
    id: 57,
    name: "skal oval stenlis/melamin",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Piring saji oval dari stainless steel atau melamin, ideal untuk menyajikan ikan bakar atau lauk memanjang.",
    available: true,
    rating: 5.0,
  },
  {
    id: 58,
    name: "tanduan stenlis",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Nampan atau tanduan dari stainless steel, kuat dan serbaguna untuk membawa atau menyajikan minuman.",
    available: true,
    rating: 5.0,
  },
  {
    id: 59,
    name: "skal oval sango",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Piring saji oval Sango berkualitas tinggi, memberikan presentasi yang elegan untuk hidangan spesial.",
    available: true,
    rating: 5.0,
  },
  {
    id: 60,
    name: "bowl kaca",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk saji dari kaca bening, cocok untuk salad buah, es, atau hidangan yang ingin ditonjolkan warnanya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 61,
    name: "bowl stenlis",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk saji dari stainless steel, tahan lama dan serbaguna untuk mencampur adonan atau menyajikan makanan.",
    available: true,
    rating: 5.0,
  },
  {
    id: 62,
    name: "bowl sango",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk saji Sango dengan kualitas keramik premium, menambah nilai estetika pada meja makan Anda.",
    available: true,
    rating: 5.0,
  },
  {
    id: 63,
    name: "bowl kuningan",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Mangkuk saji dengan sentuhan akhir kuningan, memberikan nuansa etnik dan mewah.",
    available: true,
    rating: 5.0,
  },
  {
    id: 64,
    name: "tempat kopi/gula",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Set wadah elegan untuk menyimpan kopi, gula, dan krimer di meja minuman.",
    available: true,
    rating: 5.0,
  },
  {
    id: 65,
    name: "tempat acar/saus",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Wadah kecil dengan beberapa kompartemen, ideal untuk menyajikan aneka acar, saus, atau sambal.",
    available: true,
    rating: 5.0,
  },
  {
    id: 66,
    name: "cangkir/lepek",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Set cangkir dan lepek (tatakan) klasik untuk menyajikan teh atau kopi panas.",
    available: true,
    rating: 5.0,
  },
  {
    id: 67,
    name: "gelas kaki",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Gelas berkaki (goblet), cocok untuk menyajikan air, jus, atau minuman selamat datang dengan gaya.",
    available: true,
    rating: 5.0,
  },
  {
    id: 68,
    name: "gelas",
    category: "Barang 5",
    price: "Rp xxx.xxx/hari",
    image: "/dummy.svg",
    description: "Gelas minum standar yang serbaguna, esensial untuk segala jenis minuman di setiap acara.",
    available: true,
    rating: 5.0,
  },
]